CREATE TABLE PROJECTS (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(255),
	IMG_URL VARCHAR(255),
	URL VARCHAR(255),
	REPO VARCHAR(255),
	STATUS BOOLEAN,
	STACK VARCHAR(255)
);

CREATE TABLE TIMELINE (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	YEAR INTEGER,
	DURATION VARCHAR(50),
	STATUS BOOLEAN
);

CREATE TABLE POST (
	ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(255),
	RESUME VARCHAR(800),
	CONTENT VARCHAR(8000),
	PUBLISHED BOOLEAN NOT NULL DEFAULT false,
	AUTHOR VARCHAR(30),
	CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CONTACT (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(500),
	DESCRIPTION VARCHAR(500),
	ADDRESS VARCHAR(500),
	IMG VARCHAR(800),
	STATUS BOOLEAN
);